USE [master]
GO

/****** Object:  Database [Database.Projet.Dotnet]    Script Date: 07/12/2018 18:13:23 ******/
CREATE DATABASE [Database.Projet.Dotnet]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Database.Projet.Dotnet', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Database.Projet.Dotnet.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Database.Projet.Dotnet_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Database.Projet.Dotnet_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Database.Projet.Dotnet] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Database.Projet.Dotnet].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Database.Projet.Dotnet] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Database.Projet.Dotnet] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Database.Projet.Dotnet] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Database.Projet.Dotnet] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Database.Projet.Dotnet] SET ARITHABORT OFF 
GO

ALTER DATABASE [Database.Projet.Dotnet] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Database.Projet.Dotnet] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Database.Projet.Dotnet] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Database.Projet.Dotnet] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Database.Projet.Dotnet] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Database.Projet.Dotnet] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Database.Projet.Dotnet] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Database.Projet.Dotnet] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Database.Projet.Dotnet] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Database.Projet.Dotnet] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Database.Projet.Dotnet] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Database.Projet.Dotnet] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Database.Projet.Dotnet] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Database.Projet.Dotnet] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Database.Projet.Dotnet] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Database.Projet.Dotnet] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Database.Projet.Dotnet] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Database.Projet.Dotnet] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Database.Projet.Dotnet] SET  MULTI_USER 
GO

ALTER DATABASE [Database.Projet.Dotnet] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Database.Projet.Dotnet] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Database.Projet.Dotnet] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Database.Projet.Dotnet] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Database.Projet.Dotnet] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Database.Projet.Dotnet] SET QUERY_STORE = OFF
GO

USE [Database.Projet.Dotnet]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Database.Projet.Dotnet] SET  READ_WRITE 
GO

