//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Esimed.Projet.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableJalon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TableJalon()
        {
            this.TableTache = new HashSet<TableTache>();
        }
    
        public int JalonId { get; set; }
        public Nullable<int> JalonTrigramme { get; set; }
        public Nullable<int> JalonAvancement { get; set; }
        public Nullable<System.DateTime> JalonDateDebut { get; set; }
        public Nullable<System.DateTime> JalonDateFin { get; set; }
        public string JalonNom { get; set; }
        public Nullable<int> IdProjet { get; set; }
    
        public virtual TableProjet TableProjet { get; set; }
        public virtual TableTrigramme TableTrigramme { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TableTache> TableTache { get; set; }
    }
}
