//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Esimed.Project.MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableProjet
    {
        public string ProjetId { get; set; }
        public Nullable<int> ProjetAvancement { get; set; }
        public Nullable<int> ProjetJalon { get; set; }
    
        public virtual TableJalon TableJalon { get; set; }
    }
}
