//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Esimed.Project.MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableJalon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TableJalon()
        {
            this.TableProjet = new HashSet<TableProjet>();
        }
    
        public int JalonId { get; set; }
        public Nullable<int> JalonAvancement { get; set; }
        public Nullable<int> JalonTaches { get; set; }
        public string JalonNom { get; set; }
    
        public virtual TableTache TableTache { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TableProjet> TableProjet { get; set; }
    }
}
